### PR TITLE
Main page

### PR DESCRIPTION
**Pull request by Kushalbaj**
I think I have made the main page fully responsive. Please review it and provide feedback.

I need to work on aligning the card heading and paragraph to be centered.

### CODE REVIEW

**Comment by sanjayguwaju** [comment]
> I think I have made the main page fully responsive. Please review it and provide feedback.
> 
> I need to work on aligning the card heading and paragraph to be centered.

@Kushalbaj  we will work on in together.

**Review by sanjayguwaju — COMMENTED** [review]
I think there will be some merge conficts gonna occur so we should have a meeting about it .

**Comment by sanjayguwaju** [comment]
> I think there will be some merge conficts gonna occur so we should have a meeting about it .

Let's have a google meet meet today evening

**Comment by Kushalbaj** [comment]
Okay

**Pull request merged**
