### PR TITLE
added: url-splitter project

### PR DESCRIPTION
**Pull request by sanjayguwaju**
### URL SPLITTER

- If you put url then it will spit it.

### CODE REVIEW

**Review by sanjayguwaju — COMMENTED** [review]
Okay this looks good

**Review by sanjayguwaju — COMMENTED** [review]
Okay this looks good

**Review by sanjayguwaju — COMMENTED** [review]
Okay this looks good

**Review by Kushalbaj — COMMENTED** [review]
Nice good

**Comment by sanjayguwaju** [comment]
@Kushalbaj Please review my code

**Comment by sanjayguwaju** [comment]
@sarojsy7021 can you review my code

**Pull request merged**
