### PR TITLE
add: new project text-analyzer

### PR DESCRIPTION
**Pull request by sanjayguwaju**
Yesma maile text analyzer banako xa

### CODE REVIEW

**Review by Kushalbaj — CHANGES_REQUESTED** [review]
Add spaces between head in line 11

**Comment by sanjayguwaju** [comment]
> Add spaces between head in line 11

Okay i will do it

**Comment by sanjayguwaju** [comment]
> Add spaces between head in line 11

yeah i have done it now please review it

**Review by Kushalbaj — APPROVED** [review]
All good

**Pull request merged**
